version: 2

project_name: local-agent

before:
  hooks:
    - go mod tidy

builds:
  - id: local-agent
    main: ./main.go
    binary: local-agent
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/hyuck0221/local-agent/cmd.version={{.Version}}
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE*
      - README*

checksum:
  name_template: checksums.txt

release:
  github:
    owner: hyuck0221
    name: local-agent
  draft: false
  prerelease: auto
